version: "3.7"
services:
  app:
    build:
      args:
        user: dimensy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: dimensy
    container_name: dimensy-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dimensyNetwork

  nginx:
    image: nginx:alpine
    container_name: dimensy-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - dimensyNetwork

networks:
  dimensyNetwork:
    driver: bridge